import type { LeagueCatalog, Shirt, ShirtFormState, ShirtStatus, Sport } from "./types";

export const placeholderImages: Record<Sport | "default", string> = {
  default:
    "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80",
  football:
    "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80",
  basketball:
    "https://images.unsplash.com/photo-1517649763962-0c623066013b5?auto=format&fit=crop&w=1200&q=80",
};

export const catalog: LeagueCatalog = {
  football: {
    club: {
      España: {
        "LaLiga EA Sports": [
          "Real Madrid",
          "FC Barcelona",
          "Atlético de Madrid",
          "Athletic Club",
          "Real Sociedad",
          "Villarreal CF",
          "Real Betis",
          "Sevilla FC",
          "Valencia CF",
          "Celta de Vigo",
          "Rayo Vallecano",
          "CA Osasuna",
          "Getafe CF",
          "RCD Mallorca",
          "Girona FC",
          "UD Las Palmas",
          "Deportivo Alaves",
          "RCD Espanyol",
          "Real Valladolid",
          "CD Leganes",
        ],
        "LaLiga Hypermotion": [
          "Real Zaragoza",
          "Sporting de Gijon",
          "Real Oviedo",
          "Levante UD",
          "SD Eibar",
          "Granada CF",
          "Cadiz CF",
          "Malaga CF",
          "Racing de Santander",
          "CD Tenerife",
          "UD Almeria",
          "Elche CF",
          "Burgos CF",
          "FC Cartagena",
          "CD Castellon",
          "Cordoba CF",
          "Albacete Balompie",
          "SD Huesca",
          "CD Eldense",
          "Racing de Ferrol",
        ],
      },
      Inglaterra: {
        "Premier League": [
          "Arsenal",
          "Aston Villa",
          "Bournemouth",
          "Brentford",
          "Brighton",
          "Chelsea",
          "Crystal Palace",
          "Everton",
          "Fulham",
          "Ipswich Town",
          "Leicester City",
          "Liverpool",
          "Manchester City",
          "Manchester United",
          "Newcastle United",
          "Nottingham Forest",
          "Southampton",
          "Tottenham Hotspur",
          "West Ham United",
          "Wolverhampton",
        ],
        Championship: [
          "Leeds United",
          "Burnley",
          "Sheffield United",
          "Sunderland",
          "Middlesbrough",
          "West Bromwich Albion",
          "Norwich City",
          "Watford",
          "Blackburn Rovers",
          "Coventry City",
          "Swansea City",
          "Cardiff City",
          "Millwall",
          "Preston North End",
          "Queens Park Rangers",
          "Stoke City",
          "Derby County",
          "Portsmouth",
          "Hull City",
          "Bristol City",
        ],
      },
      Italia: {
        "Serie A": [
          "Juventus",
          "Inter de Milan",
          "AC Milan",
          "Napoli",
          "AS Roma",
          "Lazio",
          "Atalanta",
          "Fiorentina",
          "Bologna",
          "Torino",
          "Genoa",
          "Udinese",
          "Cagliari",
          "Hellas Verona",
          "Empoli",
          "Lecce",
          "Parma",
          "Como",
          "Venezia",
          "Monza",
        ],
        "Serie B": [
          "Palermo",
          "Bari",
          "Sampdoria",
          "Sassuolo",
          "Cremonese",
          "Pisa",
          "Brescia",
          "Modena",
          "Spezia",
          "Cittadella",
          "Cesena",
          "Catanzaro",
          "Reggiana",
          "Frosinone",
          "Salernitana",
          "Mantova",
          "Cosenza",
          "Carrarese",
          "Juve Stabia",
          "Sudtirol",
        ],
      },
      Alemania: {
        Bundesliga: [
          "Bayern Munich",
          "Borussia Dortmund",
          "Bayer Leverkusen",
          "RB Leipzig",
          "Eintracht Frankfurt",
          "Stuttgart",
          "Wolfsburg",
          "Borussia Monchengladbach",
          "Werder Bremen",
          "Mainz 05",
          "Freiburg",
          "Augsburg",
          "Hoffenheim",
          "Union Berlin",
          "Bochum",
          "Heidenheim",
          "St. Pauli",
          "Holstein Kiel",
        ],
        "2. Bundesliga": [
          "Hamburger SV",
          "Hertha BSC",
          "Schalke 04",
          "Hannover 96",
          "Koln",
          "Fortuna Dusseldorf",
          "Nurnberg",
          "Kaiserslautern",
          "Karlsruher SC",
          "Paderborn",
          "Greuther Furth",
          "Magdeburg",
          "Darmstadt",
          "Elversberg",
          "Eintracht Braunschweig",
          "Jahn Regensburg",
          "Preussen Munster",
          "Ulm",
        ],
      },
      Francia: {
        "Ligue 1": [
          "PSG",
          "Olympique de Marsella",
          "Olympique de Lyon",
          "AS Monaco",
          "Lille",
          "Rennes",
          "Lens",
          "Niza",
          "Nantes",
          "Montpellier",
          "Toulouse",
          "Estrasburgo",
          "Reims",
          "Brest",
          "Auxerre",
          "Angers",
          "Saint-Etienne",
          "Le Havre",
        ],
        "Ligue 2": [
          "Bordeaux",
          "Paris FC",
          "Metz",
          "Lorient",
          "Caen",
          "Guingamp",
          "Grenoble",
          "Amiens",
          "Bastia",
          "Ajaccio",
          "Dunkerque",
          "Laval",
          "Pau FC",
          "Rodez",
          "Troyes",
          "Annecy",
          "Clermont",
          "Red Star",
        ],
      },
    },
    national: {
      España: { Internacional: ["España"] },
      Francia: { Internacional: ["Francia"] },
      Brasil: { Internacional: ["Brasil"] },
      Argentina: { Internacional: ["Argentina"] },
      Alemania: { Internacional: ["Alemania"] },
      Italia: { Internacional: ["Italia"] },
      Inglaterra: { Internacional: ["Inglaterra"] },
      Portugal: { Internacional: ["Portugal"] },
      "Países Bajos": { Internacional: ["Países Bajos"] },
      Bélgica: { Internacional: ["Bélgica"] },
      Croacia: { Internacional: ["Croacia"] },
      Uruguay: { Internacional: ["Uruguay"] },
      México: { Internacional: ["México"] },
      Japón: { Internacional: ["Japón"] },
      Marruecos: { Internacional: ["Marruecos"] },
    },
  },
  basketball: {
    club: {
      "Estados Unidos": {
        NBA: [
          "Atlanta Hawks",
          "Boston Celtics",
          "Brooklyn Nets",
          "Charlotte Hornets",
          "Chicago Bulls",
          "Cleveland Cavaliers",
          "Dallas Mavericks",
          "Denver Nuggets",
          "Detroit Pistons",
          "Golden State Warriors",
          "Houston Rockets",
          "Indiana Pacers",
          "LA Clippers",
          "Los Angeles Lakers",
          "Memphis Grizzlies",
          "Miami Heat",
          "Milwaukee Bucks",
          "Minnesota Timberwolves",
          "New Orleans Pelicans",
          "New York Knicks",
          "Oklahoma City Thunder",
          "Orlando Magic",
          "Philadelphia 76ers",
          "Phoenix Suns",
          "Portland Trail Blazers",
          "Sacramento Kings",
          "San Antonio Spurs",
          "Toronto Raptors",
          "Utah Jazz",
          "Washington Wizards",
        ],
      },
      España: {
        ACB: [
          "Real Madrid Baloncesto",
          "Barca Basket",
          "Baskonia",
          "Valencia Basket",
          "Unicaja Malaga",
          "Joventut Badalona",
          "BAXI Manresa",
          "Gran Canaria",
          "UCAM Murcia",
          "Casademont Zaragoza",
          "Bilbao Basket",
          "Lenovo Tenerife",
          "Basquet Girona",
          "MoraBanc Andorra",
          "Coviran Granada",
          "Rio Breogan",
          "Leyma Coruna",
          "Forca Lleida",
        ],
      },
      Europa: {
        Euroleague: [
          "Real Madrid Baloncesto",
          "Barca Basket",
          "Baskonia",
          "Olympiacos",
          "Panathinaikos",
          "Fenerbahce",
          "Anadolu Efes",
          "CSKA Moscú",
          "Partizan",
          "Estrella Roja",
          "Virtus Bologna",
          "Olimpia Milano",
          "AS Monaco Basket",
          "Zalgiris Kaunas",
          "Maccabi Tel Aviv",
          "Bayern Munich Basket",
          "ALBA Berlin",
          "ASVEL",
        ],
      },
    },
    national: {
      España: { Internacional: ["España Basket"] },
      Francia: { Internacional: ["Francia Basket"] },
      "Estados Unidos": { Internacional: ["Estados Unidos Basket"] },
      Argentina: { Internacional: ["Argentina Basket"] },
      Serbia: { Internacional: ["Serbia Basket"] },
      Canadá: { Internacional: ["Canadá Basket"] },
      Alemania: { Internacional: ["Alemania Basket"] },
      Grecia: { Internacional: ["Grecia Basket"] },
      Australia: { Internacional: ["Australia Basket"] },
      Eslovenia: { Internacional: ["Eslovenia Basket"] },
    },
  },
};

export const sportLabels = {
  football: "Fútbol",
  basketball: "Baloncesto",
};

export const categoryLabels = {
  club: "Club",
  national: "Selección",
};

export const statusLabels: Record<ShirtStatus, string> = {
  collection: "Colección",
  wishlist: "Wishlist",
};

export const kitTypes = ["Local", "Visitante", "Tercera", "Portero", "Especial"];

export const sizes = ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL"];

export const emptyFilters = {
  search: "",
  sport: "all",
  status: "all",
  country: "all",
  league: "all",
  team: "all",
  year: "",
} as const;

export const defaultForm: ShirtFormState = {
  sport: "",
  category: "",
  country: "",
  league: "",
  team: "",
  customTeam: "",
  season: "",
  player: "",
  number: "",
  kitType: "",
  size: "",
  status: "",
  images: [],
  mainImageId: "",
  notes: "",
};

export const initialShirts: Shirt[] = [
  {
    id: "shirt-1",
    sport: "football",
    category: "club",
    country: "España",
    league: "LaLiga EA Sports",
    team: "Real Madrid",
    season: "2023/24",
    player: "Bellingham",
    number: "5",
    kitType: "Local",
    size: "L",
    status: "collection",
    images: [
      {
        id: "img-1-1",
        url: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
        label: "Frontal",
      },
    ],
    mainImageId: "img-1-1",
    notes: "Parche de Champions y dorsal oficial.",
  },
  {
    id: "shirt-2",
    sport: "football",
    category: "club",
    country: "Inglaterra",
    league: "Premier League",
    team: "Liverpool",
    season: "2024/25",
    player: "Salah",
    number: "11",
    kitType: "Visitante",
    size: "M",
    status: "collection",
    images: [
      {
        id: "img-2-1",
        url: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80",
        label: "Frontal",
      },
    ],
    mainImageId: "img-2-1",
    notes: "Buen estado general.",
  },
  {
    id: "shirt-3",
    sport: "basketball",
    category: "club",
    country: "Estados Unidos",
    league: "NBA",
    team: "Los Angeles Lakers",
    season: "2023/24",
    player: "James",
    number: "23",
    kitType: "Local",
    size: "XL",
    status: "wishlist",
    images: [
      {
        id: "img-3-1",
        url: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
        label: "Frontal",
      },
    ],
    mainImageId: "img-3-1",
    notes: "Swingman edition.",
  },
  {
    id: "shirt-4",
    sport: "football",
    category: "national",
    country: "Argentina",
    league: "Internacional",
    team: "Argentina",
    season: "2022",
    player: "Messi",
    number: "10",
    kitType: "Local",
    size: "M",
    status: "wishlist",
    images: [
      {
        id: "img-4-1",
        url: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=1200&q=80",
        label: "Frontal",
      },
    ],
    mainImageId: "img-4-1",
    notes: "Modelo mundialista.",
  },
  {
    id: "shirt-5",
    sport: "basketball",
    category: "club",
    country: "España",
    league: "ACB",
    team: "Real Madrid Baloncesto",
    season: "2024/25",
    player: "Campazzo",
    number: "7",
    kitType: "Local",
    size: "L",
    status: "collection",
    images: [
      {
        id: "img-5-1",
        url: "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=1200&q=80",
        label: "Frontal",
      },
    ],
    mainImageId: "img-5-1",
    notes: "Comprada en tienda oficial.",
  },
];
